spring:
    datasource:
        url: jdbc:mysql://115.28.134.96:3406/deve?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
        username: dev
        password: java-war
        driver-class-name: com.mysql.jdbc.Driver

    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

